name: MP-Linksammlung create docker image

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: docker login
        env:
          REGISTRY_USER: ${{ secrets.REGISTRY_USER }}
          REGISTRY_PWD: ${{ secrets.REGISTRY_PWD }}
          REGISTRY_URL: ${{ secrets.REGISTRY_URL }}
        run: docker login $REGISTRY_URL -u $REGISTRY_USER -p $REGISTRY_PWD
           
      - name: build docker image
        env:
          REGISTRY_URL: ${{ secrets.REGISTRY_URL }}
        run: |
          docker build -t $REGISTRY_URL/mp_linksammlung:alpha .
          
      - name: docker push
        env:
          REGISTRY_URL: ${{ secrets.REGISTRY_URL }}
        run: docker push $REGISTRY_URL/mp_linksammlung:alpha

      - name: Portainer Webhook - Update Service
        run: curl --request POST ${{ secrets.PORTAINER_WEBHOOK }}  